version: "3.8"
services:

  triangle-db:
    container_name: triangle-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${AUTH_DATABASE_USER}
      - POSTGRES_PASSWORD=${AUTH_DATABASE_PASSWORD}
      - POSTGRES_DB=${AUTH_DATABASE_DB}
    ports:
      - '5432:5432'