version: "3.8"
services:

  triangle-mysql:
    container_name: triangle-mysql
    image: mysql:5.6.26
    environment:
      - MYSQL_ROOT_PASSWORD=asdqwe123
      - MYSQL_DATABASE=triangle
    ports:
      - "3306:3306"

  triangle-classification:
    image: 'triangle-classification:latest'
    environment:
      - ENV=local
    build:
      context: .
    container_name: triangle-classification
    ports:
      - "8090:8090"
    depends_on:
      - triangle-mysql