version: "3.8"
services:

  triangle-mysql:
    container_name: triangle-mysql
    image: mysql:5.6.26
    environment:
      - MYSQL_ROOT_PASSWORD=asdqwe123
      - MYSQL_DATABASE=triangle-db
    ports:
      - "3306:3306"